apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  containers:
  - name: secret-container-xfusion
    image: debian:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - mountPath: "/opt/games"
        name: news
        readOnly: true
  volumes:
    - name: news
      secret:
        secretName: news
