apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-container-devops-pod
  labels:
    app: secret-container-devops-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-wp
  template:
    metadata:
      labels:
        app: lamp-wp
    spec:
      containers:
      - name: secret-container-devops
        image: fedora:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - mountPath: "/opt/demo"
            name: blog
            readOnly: true
      volumes:
        - name: blog
          secret:
            secretName: blog
